kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmaps-role-binding
  namespace: k8
subjects:
- kind: ServiceAccount
  name: configmaps
  namespace: k8
roleRef:
  kind: Role
  name: configmaps
  apiGroup: rbac.authorization.k8s.io
