kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: k8
  name: configmaps
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "pods", "configmaps", "services", "endpoints"]
  verbs: ["get", "update", "patch", "create", "list"]
