spring.application.name: configmaps

spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health
