apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: users-service
      docker:
        dockerfile: Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
#      - deploy.yaml
      - testservice.yaml
      - test.yaml
portForward:
  - resourceType: deployment
    resourceName: users-service
    port: 8080
    localPort: 9000