kind: Service
apiVersion: v1
metadata:
  name: configserver
  namespace: k8
spec:
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30084
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  namespace: k8
spec:
  selector:
    matchLabels:
      app: configserver
  replicas: 1
  template:
    metadata:
      labels:
        app: configserver
    spec:
      serviceAccountName: configmaps
#      dnsPolicy: Default
#      hostNetwork: true # dont user hostnetwork for server as its not calling api server
      containers:
        - name: configserver
          image: rakgenius/configserver:0.0.10
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
