apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: rakgenius/users-service:2326329-dirty
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080