kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: default
rules:
  - apiGroups: [""]
    resources: ["deployments", "pods", "configmaps", "services", "endpoints"]
    verbs: ["get", "update", "patch", "create", "list"]
