# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: books-bestseller
  name: books-bestseller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: books-bestseller-exposed
  template:
    metadata:
      labels:
        run: books-bestseller-exposed
    spec:
      serviceAccountName: chaos
      containers:
        - image: rakgenius/bestseller-books
          name: books-bestseller
          ports:
            - containerPort: 8084
              protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: books-bestseller
  name: books-bestseller
spec:
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    run: books-bestseller-exposed
  type: NodePort
