server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/ravening/spring-cloudconfig-watolls
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/ravening/spring-cloudconfig-watolls-perf
              search-paths:
                - 'station*'
  security:
    user:
      password: pluralsight
      name: pluralsight
#          username:
#          password: